config/routes.rb
Rails.application.routes.draw do

  # 管理者用
  devise_for :admin,skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: 'homes#top'
    get 'search' =>"searches#search"
    resources :customers
    resources :posts do
      # resource :favorites, only: [:destroy]
      resources :comments, only: [:destroy]
    end

  end

  # ユーザー用
  devise_for :customers,controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions',
    passwords: 'public/passwords'
  }

  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    root to: 'homes#top'
    resources :notifications, only: :index
    get 'about'=>"homes#about",as: "about"
    get 'search' =>"searches#search"
    get 'favorites_ranking' =>"posts#favorites_ranking"
    get 'follow_posts' =>"posts#follow_posts"
    get 'my_posts' =>"posts#my_posts"
    resources :posts do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end

    resources :customers do
      member do
        get :favorites
      end
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'

    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :spot

  validates :account_name, uniqueness: true, length: { minimum:2 , maximum:20}
  validates :introduction, length: {maximum:200}



  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
    # SQLのエラーが出てしまったため、クラス指定をしております。
  has_many :favorites, dependent: :destroy, class_name: "Favourite"
  has_many :liked_posts, through: :favorites, source: :post

  # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower

  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed

  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy




  def follow(customer)
    relationships.create(followed_id: customer.id)
  end

  def unfollow(customer)
    relationships.find_by(followed_id: customer.id).destroy
  end

  def following?(customer)
    followings.include?(customer)
  end


  has_one_attached :profile_image
  # プロフィール画像がなかった場合の設定、サイズの調整のためのメゾットです。
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/animal_chara_radio_penguin.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  # ゲストログインのためのメゾットです。
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.account_name = "ゲスト"
      customer.spot_id = 1
      customer.introduction = "ゲストです"
    end
  end

  # 検索のためのメゾットです。
  def self.search_for(content, method, spot_id)
    customers =
    if content.blank?
      Customer.all
    else
      if method == 'perfect'
        Customer.where(account_name: content)
      elsif method == 'forward'
        Customer.where('account_name LIKE ?', content + '%')
      elsif method == 'backward'
        Customer.where('account_name LIKE ?', '%' + content)
      else
        Customer.where('account_name LIKE ?', '%' + content + '%')
      end
    end
    spot_id.blank? ? customers : customers.where(spot_id: spot_id)
    #spot_id.blank? ? ~~ は下記と同じ内容です。
    #if spot_id.blank?
      #customers
    #else
      #csutomers.where()
    #end
  end

    def create_notification_follow!(current_customer)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_customer.id, id, 'follow'])
    if temp.blank?
      notification = current_customer.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end


end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < Admin::ApplicationController


  def new
  end
  def index
    @customers = Customer.page(params[:page]).order(created_at: "DESC")
  end

  def show
    @customer = Customer.find(params[:id])
    @posts = @customer.posts.page(params[:page])
  end

  def edit
    @customer = Customer.find(params[:id])
    @spot_id_pair = Spot.pluck('spot_name, id').to_h
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash.now[:notice] = "編集に成功しました!"
      redirect_to admin_customer_path(@customer.id)
    else
      @spot_id_pair = Spot.pluck('spot_name, id').to_h
      render :edit

    end
  end

  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy
    redirect_to admin_root_path
  end


private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana,:email,:account_name,:profile_image,:spot_id, :phone_number, :introduction, :is_deleted)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container py-5">
 <div class="row">
  <div class="col">
   <h2 class="m-4 text-center font-weight-bold"><%= @customer.account_name %>さんの会員情報編集</h2>
    <% if @customer.errors.any? %>
     <%= @customer.errors.count %>件のエラーが発生しました
    <ul>
     <% @customer.errors.full_messages.each do |message| %>
      <li><%= message %></li>
     <% end %>
    </ul>
    <% end %>
  </div>
    
   <table class="table table-striped text-center"  style="color:white;">
    <%= form_with model: [:admin, @customer], local: true do |f| %>
    
     <tr>
      <div class="field">
       <th><%= f.label "アカウント名" %></th>
       <td><%= f.text_field :account_name , autofocus: true %></td>
       <td></td>
      </div>
     </tr>
     
     <tr>
      <div class="field">
       <th><%= f.label "プロフィール画像" %></th>
       <td><%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %></td>
       <td></td>
      </div>
     </tr>
     <tr>
      <div class="field">
       <th><%= f.label "居住地" %></th>
       <td>
       <!--@spot_id_pairでspot_nameをidに変換しております。-->
       <%= f.select :spot_id, Spot.spot_names.keys.map {|k| [I18n.t("enums.spot.spot_name.#{k}"), @spot_id_pair[k]]}, include_blank: "選択して下さい"  %>
       </td>
       <td></td>
      </div>
     </tr>
     
     <tr>
      <div class="field">
       <th><%= f.label "自己紹介" %></th>
       <td><%= f.text_area :introduction %></td>
       <td></td>
      </div>
     </tr>
     
     <tr>
      <div class="field">
       <th><%= f.label "メールアドレス" %></th>
       <td><%= f.email_field :email, autocomplete: "email" %><td>
       <td></td>
      </div>
     </tr>
     
     <tr>
      <div class="field">
       <th><%= f.label "電話番号" %></th>
       <td><%= f.text_field :phone_number %><td>
       <td></td>
      </div>
     </tr>
     
     <tr>
      <div class="field">
       <th>名前（姓・名）</th>
       <td><%= f.text_field :last_name %></td>
       <td><%= f.text_field :first_name %></td>
      </div>
     </tr>
     <tr>
      <div class="field">
       <th>フリガナ</th>
       <td><%= f.text_field :last_name_kana %></td>
       <td><%= f.text_field :first_name_kana %></td>
      </div>
     </tr>
     
     
     <tr>
      <td>  <%= f.submit "編集内容を保存する", class: "btn btn-primary" %></td>
      <td></td>
      <td>   <%= link_to "退会する", admin_customer_path, class: "btn btn-danger", method: :delete, data: { confirm: '本当に削除しますか?' } %></td>
     </tr>
    <% end %>
   </table>
   <%= link_to "ユーザー一覧に戻る",admin_customer_path(@customer.id), class: "btn btn-primary" %>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
 <div class="row">
  <div class="col">
   <h4 class="m-4 text-center font-weight-bold">会員一覧</h4>
  </div>
  <table class="table text-center" style="color:white;">
   <thead class="thead-dark">
     <tr>
       <th scope="col">会員ID</th>
       <th scope="col">プロフィール画像</th>
       <th scope="col">氏名</th>
       <th scope="col">アカウントネーム</th>
       <th scope="col">メールアドレス</th>
      </tr>
   </thead>

   <tbody>
    <% @customers.each do |customer| %>
     <tr>
      <th scope="row"><%= customer.id %></th>
      <td>
       <%= link_to admin_customer_path(customer), class: "text-white" do %>
      <p>ユーザー画像：<%= image_tag customer.get_profile_image(100,100) %></p></td>
      <td><%= customer.last_name %><% customer.first_name %></td>
      <td><%= customer.account_name %></td>
      <td><%= customer.email %></td>
       <% end %>
     </tr>
    <% end %>
   </tbody>
  </table>
 </div>
 <div class="row justify-content-center mt-3">
  <div class='mr-5'>
   <%= paginate @customers %>
   </div>
 </div>
</div>

app/views/admin/customers/new.html.erb
<h1>Admin::Customers#new</h1>
<p>Find me in app/views/admin/customers/new.html.erb</p>

app/views/admin/customers/show.html.erb
<div class="profile-container border-bottom py-3">
  <div class="row text-center">
    <div class="col-md-12"><h1>ユーザー詳細ページ</h1></div>
  </div>

  <div class="row">
    <div class="mx-auto "><%= image_tag @customer.get_profile_image(250,250), class:"rounded-circle"; %></div>
  </div>
  <div class=" text-center ">
    <h5>ユーザーネーム：<%= @customer.account_name %></h5>
  </div>
  <div class=" text-center">
    <h5>自己紹介：<%= @customer.introduction %></h5>
  </div>
  <div class=" text-center">
    <h5>居住地：<%= @customer.spot.spot_name_i18n %></h5>
  </div>

  <div class=" text-center">
    <h5>follows<%= @customer.followings.count %></h5>
  </div>
  <div class=" text-center">
    <h5>followers<%= @customer.followers.count %></h5>
  </div>

  <div class=" text-center">
     <h5><%= link_to "プロフィール編集", edit_admin_customer_path(@customer) %></h5>
  </div>
</div>



<% @posts.each do |post| %>

<div class="text-center">
  <div class="card-list-containar py-5">
    <div class="card w-50 mx-auto mt-4 shadow-lg">
      <div class="container">
        <div id="carouselExampleControls_<%= post.id %>" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <% post.get_images.each_with_index do |image, index| %>
              <div class="carousel-item<%= index == 0 ? ' active' : ''%>">
                <%= image_tag image, style: 'width: 100%; height: 800px; object-fit: cover;' %>
              </div>
            <% end %>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleControls_<%= post.id %>" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleControls_<%= post.id %>" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>


    <div class="card-body">
      <div class="row">
        <div class="col-12">
          <p class="card-title"><%= link_to admin_post_path(post) do %><%= post.title %><% end %></p>
          <p class="card-text"><%= post.spot.spot_name_i18n %></p>
          <p class="card-text"><% post.tag_list.each do |tag| %>
       <span class="badge badge-primary mr-1 p-2 ">
         <%= link_to admin_posts_path(tag_name: tag) ,class:"text-white" do %>
           <%= tag %>
         <% end %></span>
       <% end %></p>
       <p class="card-text"><div id="rate_<%= post.id %>"></div></p>
       <p class="card-text"></p>
       <p class="card-text"><%= link_to "#{post.comments.count} コメント", admin_post_path(post.id) %></p>
      </div>

      <script>
      $(function(){


          let raty_show<%= post.id %> = document.querySelector('#rate_show<%= post.id %>');
          rate_show<%= post.id %>.innerHTML = ""
          let option_show<%= post.id %> = {
              starOn: "<%= asset_path('star-on.png') %>",
              starOff: "<%= asset_path('star-off.png') %>",
              starHalf: "<%= asset_path('star-half.png') %>",
              score: "<%= post.rate %>",
              readOnly: true,
            };
          raty(raty_show<%= post.id %> ,option_show<%= post.id %>);
      });
      </script>

      </div>
    </div>
    </div>
  </div>
</div>
<% end %>

<p><%= link_to"ユーザー一覧に戻る",admin_customers_path %> </p>


<%= paginate @posts, theme: 'twitter-bootstrap-4'   %>