config/routes.rb
Rails.application.routes.draw do

  # 管理者用
  devise_for :admin,skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: 'homes#top'
    get 'search' =>"searches#search"
    resources :customers
    resources :posts do
      # resource :favorites, only: [:destroy]
      resources :comments, only: [:destroy]
    end

  end

  # ユーザー用
  devise_for :customers,controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions',
    passwords: 'public/passwords'
  }

  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    root to: 'homes#top'
    resources :notifications, only: :index
    get 'about'=>"homes#about",as: "about"
    get 'search' =>"searches#search"
    get 'favorites_ranking' =>"posts#favorites_ranking"
    get 'follow_posts' =>"posts#follow_posts"
    get 'my_posts' =>"posts#my_posts"
    resources :posts do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end

    resources :customers do
      member do
        get :favorites
      end
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'

    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/searches_controller.rb
class Admin::SearchesController < Admin::ApplicationController

  	def search
		@model = params[:model]
		@content = params[:content]
		@method = params[:method]
		@spot_id = params[:spot_id]
		if @model == 'customer'
			@records = Customer.search_for(@content, @method, @spot_id)
		else
			@records = Post.search_for(@content, @method, @spot_id)
		end
	end
end

app/views/admin/searches/_form.html.erb
<% if admin_signed_in? %>
  <%= form_with url: admin_search_path, method: :get, local: true do |f| %>
    <%= f.text_field :content %>
    <%= f.select :model, options_for_select({ "ユーザー" => "customer", "投稿タイトル" => "post" }) %>
    <%= f.select :method, options_for_select({ "完全一致" => "perfect", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partial" }) %>
    <%= f.select :spot_id, Spot.spot_names.keys.map {|k| [I18n.t("enums.spot.spot_name.#{k}"), Spot.pluck('spot_name, id').to_h[k]]}, include_blank: "選択して下さい"  %>
    <%= f.submit '検索' %>
  <% end %>
<% end %>

app/views/admin/searches/search.html.erb
<% if @model == 'customer' %>
  <div class="index-background-image">
    <div class="container">
      <div class="row">
        <div class="col">
          <h2 class="m-4 text-center font-weight-bold">ユーザー検索結果 "<%= @content %>"</h2>
        </div>
        <table class="table text-center" style="color:white;">
          <thead class="thead-dark">
            <tr>
              <th scope="col">ユーザー画像</th>
              <th scope="col">ユーザーネーム</th>
              <th scope="col">自己紹介</th>
              <th scope="col">居住地</th>
              <th scope="col">フォロー</th>
              <th scope="col">フォロワー数</th>
              <th scope="col">フォロワーズ数</th>
            </tr>
          </thead>

          <tbody>
            <% @records .each do |customer| %>
              <tr>
                <td>
                  <%= link_to admin_customer_path(customer.id) do %>
                  <%= image_tag customer.get_profile_image(100,100), class:"rounded-circle"; %>
                  <% end %>
                </td>
                <td>
                  <%= customer.account_name %>
                </td>
                <td>
                  <%= customer.introduction %>
                </td>
                <td>
                  <%= customer.spot.spot_name_i18n %>
                </td>
                <td>
                  <%= link_to customer.followings.count %>
                </td>
                <td>
                  <%= link_to customer.followers.count %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
        <div class="row justify-content-center mt-3">
          <div class='mr-5'>
            <%= link_to"HOMEに戻る",admin_root_path %>
          </div>
        </div>

      <div class="row justify-content-center mt-3"></div>
    </div>
  </div>




<% elsif @model == 'post' %>


<h2 class="text-center font-weight-bold">投稿検索結果 "<%= @content %>"</h2>

<% @records.each do |post| %>
  <div class="text-center">
    <div class="card-list-containar py-5">
      <div class="card w-50 mx-auto mt-4 shadow-lg">
        <div class="container">
          <div id="carouselExampleControls_<%= post.id %>" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
              <% post.get_images.each_with_index do |image, index| %>
                <div class="carousel-item<%= index == 0 ? ' active' : ''%>">
                  <%= image_tag image, style: 'width: 100%; height: 800px; object-fit: cover;' %>
                </div>
              <% end %>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleControls_<%= post.id %>" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls_<%= post.id %>" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-2">
              <%= link_to admin_customer_path(post.customer.id) do %>
                <%= image_tag post.customer.get_profile_image(100,100) , class:"mt-3 rounded-circle"; %>
              <% end %>
              <p><%= post.customer.account_name %></p>
              <p><%= post.customer.spot.spot_name_i18n %></p>
            </div>
            <div class="col-10">
              <p class="card-title"><%= link_to admin_post_path(post) do %><%= post.title %><% end %></p>
              <p class="card-text"><%= post.spot.spot_name_i18n %></p>
              <p class="card-text"><% post.tag_list.each do |tag| %>
                <span class="badge badge-primary mr-1 p-2 ">
                  <%= link_to admin_posts_path(tag_name: tag) ,class:"text-white" do %>
                    <%= tag %>
                <% end %></span>
              <% end %></p>
              <p class="card-text"><div id="rate_<%= post.id %>"></div></p>

              <p class="card-text"><%= link_to "#{post.comments.count} コメント", admin_post_path(post.id) %></p>
            </div>
          <script>
            $(function(){

            let raty_<%= post.id %> = document.querySelector('#rate_<%= post.id %>');
            rate_<%= post.id %>.innerHTML = ""
            let option_<%= post.id %> = {
            starOn: "<%= asset_path('star-on.png') %>",
            starOff: "<%= asset_path('star-off.png') %>",
            starHalf: "<%= asset_path('star-half.png') %>",
            score: "<%= post.rate %>",
            readOnly: true,
            };
            raty(raty_<%= post.id %> ,option_<%= post.id %>);
            });
            </script>

        </div>
      </div>
    </div>
  </div>
</div>
<% end %>
<% end %>
<p><%= link_to"HOMEに戻る",admin_root_path %> </p>