config/routes.rb
Rails.application.routes.draw do

  # 管理者用
  devise_for :admin,skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: 'homes#top'
    get 'search' =>"searches#search"
    resources :customers
    resources :posts do
      # resource :favorites, only: [:destroy]
      resources :comments, only: [:destroy]
    end

  end

  # ユーザー用
  devise_for :customers,controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions',
    passwords: 'public/passwords'
  }

  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    root to: 'homes#top'
    resources :notifications, only: :index
    get 'about'=>"homes#about",as: "about"
    get 'search' =>"searches#search"
    get 'favorites_ranking' =>"posts#favorites_ranking"
    get 'follow_posts' =>"posts#follow_posts"
    get 'my_posts' =>"posts#my_posts"
    resources :posts do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end

    resources :customers do
      member do
        get :favorites
      end
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'

    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :customer
  belongs_to :spot   # , optional:true
  # SQLのエラーが出てしまったため、クラス指定をしております。
  has_many :favorites, dependent: :destroy, class_name: "Favourite"
  has_many :liked_customers, through: :favorites, source: :customer
  has_many :comments, dependent: :destroy
  has_many :post_tags
  has_many :notifications, dependent: :destroy


  validates :latitude, presence:true
  validates :longitude, presence:true
  validates :title, presence:true
  validates :post_content, presence:true
  # validates :spot_id, presence:true
  # レートの評価を1以上~5以下に設定しています。
  validates :rate, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1
  }, presence: true

  # 写真の投稿制限のためのメゾットを呼び出しております。
  validate :image_type, :image_size, :image_length



acts_as_taggable_on :tags



  has_many_attached :images
# 投稿画像がなかった場合のメゾットです。
  def get_images
    unless images.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      images.attach(io:File.open(file_path),filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    images
  end

def favorited_by?(customer)
  favorites.exists?(customer_id: customer.id)
end

  # 検索のためのメゾットです。
  def self.search_for(content, method, spot_id)
    spots =
      if content.blank?
        Post.all
      else
        if method == 'perfect'
          Post.where(title: content)
        elsif method == 'forward'
          Post.where('title LIKE ?', content+'%')
        elsif method == 'backward'
          Post.where('title LIKE ?', '%'+content)
        else
          Post.where('title LIKE ?', '%'+content+'%')
        end
      end
    spot_id.blank? ? spots : spots.where(spot_id: spot_id)
  end


  def create_notification_like!(current_customer)
    # すでに「いいね」されているか検索
    temp = Notification.where(["visitor_id = ? and visited_id = ? and post_id = ? and action = ? ", current_customer.id, customer_id, id, 'like'])
    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_customer.active_notifications.new(
        post_id: id,
        visited_id: customer_id,
        action: 'like'
      )
      # 自分の投稿に対するいいねの場合は、通知済みとする
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end




     def create_notification_comment!(current_customer, comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = Comment.select(:customer_id).where(post_id: id).where.not(customer_id: current_customer.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_customer, comment_id, temp_id['customer_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_comment!(current_customer, comment_id, customer_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_customer, comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_customer.active_notifications.new(
      post_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end


private

  def image_type
    images.each do |image|
      if !image.blob.content_type.in?(%('image/jpeg image/png'))
        errors.add(:images, 'はjpegまたはpng形式でアップロードしてください')
      end
    end
  end

  def image_size
    images.each do |image|
      if image.blob.byte_size > 5.megabytes
        errors.add(:images, "は1つのファイル5MB以内にしてください")
      end
    end
  end

  def image_length
    if images.length > 3
      errors.add(:images, "は3枚以内にしてください")
    end
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::ApplicationController


  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def index
      @tags = Post.tag_counts_on(:tags).order('count DESC')
    if @tag = params[:tag_name]   # タグ検索用
      @posts = Post.tagged_with(@tag).page(params[:page]).order("created_at DESC")
    else
      @posts = Post.page(params[:page]).order("created_at DESC")
    end
  end

  def edit
    @post = Post.find(params[:id])
    #@spot_id_pairでハッシュを使い、spot_nameをidに変換しております。
    @spot_id_pair = Spot.pluck('spot_name, id').to_h
  end


  def update
    @post = Post.find(params[:id])
    if  @post.update(post_params)
      flash[:notice] = "編集に成功しました！"
      redirect_to admin_post_path(@post.id)
    else
      @spot_id_pair = Spot.pluck('spot_name, id').to_h
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = "削除が完了しました"
    redirect_to admin_posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :post_content, :latitude, :longitude, :rate, :tag_list, :spot_id, images: [])
  end


end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/_index.html.erb
<% if tags.present? %>

  <% tags.each do |tag| %>
    <span class="badge badge-primary mr-1 p-2  ">
      <%= link_to "#{tag.name}(#{tag.taggings_count})", admin_posts_path(tag_name: tag.name) ,class:"text-white"  %>
    </span>
  <% end %>

<% else %>
  <p> 登録されているタグはありません </p>
<% end %>

<% if tag.present? %>
  <p class="text-center">"<%= tag %>"の検索結果</p>
<% end %>

<% posts.each do |post| %>
  <div class="text-center">
    <div class="card-list-containar py-5">
      <div class="card w-50 mx-auto mt-4 shadow-lg">
        <div class="container">
          <div id="carouselExampleControls_<%= post.id %>" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
              <% post.get_images.each_with_index do |image, index| %>
                <div class="carousel-item<%= index == 0 ? ' active' : ''%>">
                  <%= image_tag image, style: 'width: 100%; height: 800px; object-fit: cover;' %>
                </div>
              <% end %>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleControls_<%= post.id %>" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls_<%= post.id %>" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
        </div>
      <div class="card-body">
        <div class="row">
          <div class="col-2">
            <%= link_to admin_customer_path(post.customer.id) do %>
              <%= image_tag post.customer.get_profile_image(100,100) , class:"mt-3 rounded-circle"; %>
            <% end %>
            <p><%= post.customer.account_name %></p>
            <p><%= post.customer.spot.spot_name_i18n %></p>
          </div>
        <div class="col-10">
          <p class="card-title"><%= link_to admin_post_path(post) do %><%= post.title %><% end %></p>
          <p class="card-text"><%= post.spot.spot_name_i18n %></p>
          <p class="card-text"><% post.tag_list.each do |tag| %>
       <span class="badge badge-primary mr-1 p-2 ">
         <%= link_to admin_posts_path(tag_name: tag) ,class:"text-white" do %>
           <%= tag %>
          <% end %></span>
         <% end %></p>
       <p class="card-text"><div id="rate_<%= post.id %>"></div></p>
       <p class="card-text"><%= link_to "#{post.comments.count} コメント", admin_post_path(post.id) %></p>
      </div>
    
    <script>
    $(function(){
    
        let raty_<%= post.id %> = document.querySelector('#rate_<%= post.id %>');
        rate_<%= post.id %>.innerHTML = ""
        let option_<%= post.id %> = {
            starOn: "<%= asset_path('star-on.png') %>",
            starOff: "<%= asset_path('star-off.png') %>",
            starHalf: "<%= asset_path('star-half.png') %>",
            score: "<%= post.rate %>",
            readOnly: true,
          };
        raty(raty_<%= post.id %> ,option_<%= post.id %>);
    });
    </script>

    </div>
  </div>
  </div>
  </div>
</div>
<% end %>

<p><%= link_to"HOMEに戻る",admin_root_path %> </p>

app/views/admin/posts/edit.html.erb
<div class="container py-5">
 <div class="row">
   <div class="col">
     <h2 class="m-4 text-center font-weight-bold">画像投稿フォーム</h2>
     <% if @post.errors.any? %>
  <%= @post.errors.count %>件のエラーが発生しました
  <ul>
    <%# binding.irb %>
    <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
</div>

<div class="container" >
  <%= form_with model: @post, url: admin_post_path, method: :patch, local: true do |f| %>

    <table class="table table-striped text-center"  style="color:white;">
      <tr>
        <div class="field">
          <th><%= f.label "画像" %></th>
          <td><%= f.file_field :images, accept: "image/*",multiple: true %></td>
        </div>
      </tr>

      <tr>
        <div class="field">
          <th><%= f.label "タイトル" %></th>
          <td><%= f.text_field :title %></td>
        </div>
      </tr>

      <tr>
        <div class="field">
          <th><%= f.label "投稿内容" %></th>
          <td><%= f.text_area :post_content %></td>
        </div>
      </tr>

      <tr>
        <div class="field">
          <th><%= f.label "遊んだ場所" %></th>
          <td> <%= f.select :spot_id, Spot.spot_names.keys.map {|k| [I18n.t("enums.spot.spot_name.#{k}"), @spot_id_pair[k]]}, include_blank: "選択して下さい"  %>
          </td>
        </div>
      </tr>

      <tr>
        <div class="field">
          <td><div class="form-group" id="star"><%= f.label :rate %><%= f.hidden_field :rate, id: :review_star, class:'form-control' %></div></td>
        </div>

      </tr>

      <tr>
        <div class="field">
          <th><%= f.label :tag_list , class: "col-sm-2 control-label"%>（,で区切って記載ください。）</th>
          <td><%= f.text_field :tag_list, value: @post.tag_list.join(',') %></td>
        </div>
      </tr>


    </table>


    <%= f.hidden_field :latitude, :value => @post.latitude ,id: 'lat' %>
    <%= f.hidden_field :longitude, :value => @post.longitude ,id: "lng" %>

    <%= f.submit "編集内容を保存する", class: "btn btn-primary" %>
  <% end %>
</div>
<%= link_to"戻る",admin_post_path(@post.id) %>
</div>
</div>


<script>
  let raty_elem = document.querySelector('#star');
  raty_elem.innerHTML = ""
  let option = {
      starOn: "<%= asset_path('star-on.png') %>",
      starOff: "<%= asset_path('star-off.png') %>",
      starHalf: "<%= asset_path('star-half.png') %>",
      scoreName: 'post[rate]',
      score: "<%= @post.rate %>",
    };
  raty(raty_elem,option);
</script>


<div class="container py-5">
  <h4 class="m-4 text-center font-weight-bold">マップ（場所の登録をしてください）</h4>

  <input id="address" type="textbox" value="東京駅" placeholder="ここに入力してください。">
  <input type="button" value="登録" onclick="codeAddress()">

<!--<div id="display"></div>-->

  <div id='map'></div>

  <style>
  #map {
    height: 600px;
    width: 100%;
  }
  </style>
</div>

<script>
let map
function initMap(){
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
    center: {lat: 35.681236, lng:139.767125},
    zoom: 12,
  });

  marker = new google.maps.Marker({
    position:  {lat: 35.681236, lng:139.767125},
    map: map
  });
}

window.initMap = initMap;

// ここから追加
let geocoder
// const display = document.getElementById('display')

function codeAddress(){
  let inputAddress = document.getElementById('address').value;

  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
    if (status == 'OK') {
      map.setCenter(results[0].geometry.location);
      var marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
      });

      // display.textContent = "検索結果：" + results[ 0 ].geometry.location
      let location = results[0].geometry.location;
      　if (location !== null){
            document.getElementById('lat').value = location.lat();
            document.getElementById('lng').value = location.lng();
      　}
    } else {
      alert('該当する結果がありませんでした：' + status);
    }
  });
}
// ここまで追加

</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap" async defer></script>



</div>

app/views/admin/posts/index.html.erb
<h1>投稿新規順</h1>

<%= render "index", posts: @posts , tags: @tags , tag: @tag %>

<%= paginate @posts, theme: 'twitter-bootstrap-4'  %>

app/views/admin/posts/show.html.erb
<div class="container">
  <h2 class="m-4 text-center font-weight-bold">投稿詳細</h2>

  <div class="row">
    <div class="col-md-6 ">
      <table class="table "style="color:white; text-align: center;">
        <tbody>

          <tr>

            <th>投稿ユーザー画像</th>

            <td><%= link_to admin_customer_path(@post.customer.id) do %>
            <%= image_tag @post.customer.get_profile_image(100,100) %>
            <% end %></td>

          </tr>
          <tr>
            <th>ユーザーネーム</th>
            <td><%= @post.customer.account_name %></td>
          </tr>
          <tr>
            <th>ユーザー居住地</th>
            <td><%= @post.customer.spot.spot_name_i18n %></td>
          </tr>
          <tr>
            <th>タイトル</th>
            <td><%= @post.title %></td>
          </tr>
          <tr>
            <th>説明</th>
            <td><%= simple_format(@post.post_content) %></td>
          </tr>
          <tr>
          <th>遊んだ場所</th>
            <td><%= @post.spot.spot_name_i18n %></td>
          </tr>
            <tr>
          <th>評価</th>
            <td><div id="rate_show<%= @post.id %>"></div></td>
          </tr>
          <tr>
            <th>投稿日</th>
            <td><%= @post.created_at.strftime('%Y/%m/%d') %></td>
          </tr>
          <tr>
            <td>
              <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                  <% @post.get_images.each_with_index do |image, index| %>
                  <div class="carousel-item<%= index == 0 ? ' active' : ''%>">
                    <%= image_tag image, style: 'width: 100%; height: 300px; object-fit: cover;' %>
                  </div>
                  <% end %>
                </div>
              <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
            </div>
            </td>
           </tr>
        </tbody>
      </table>
    </div>
    <div class="col-md-6 mt-3 mt-md-0">
      <div id='map'></div>
    </div>
  </div>
</div>


<div class="container">
  <div style="text-align:center;">
   <div>タグ一覧：<% @post.tag_list.each do |tag| %>
     <div class="badge badge-primary mr-1 p-2 ">
      <%= link_to admin_posts_path(tag_name: tag), class: "text-white" do %>
        <%= tag %>
      <% end %></div>
   <% end %></div>
    <div class="comments-counter">
      <%= render "admin/comments/counter", post: @post %>
    </div>

    <div class="comments-index">
      <%= render "admin/comments/index", post: @post %>
    </div>

    <%= link_to "編集する", edit_admin_post_path(@post) %>
    <%= link_to "投稿を削除する", admin_post_path, class: "btn btn-danger", method: :delete, data: { confirm: '本当に削除しますか?' } %>


    <p><%= link_to"投稿一覧に戻る",admin_posts_path %> </p>

  </div>
</div>

<style>
#map {
  height: 800px;
  width: 100%;
}
</style>

<script>
let map

function initMap(){
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
    center: {lat: <%= @post.latitude.to_f %>, lng: <%= @post.longitude.to_f %>},
    zoom: 12,
  });

  const contentString =
    '説明：<%= simple_format(@post.post_content) %>' +
    '選んだ場所：<%= @post.spot.spot_name_i18n %><br>' +
    '<a target="_blank" rel="noopener noreferrer" href="https://www.google.co.jp/maps/?q=<%= @post.latitude.to_f %>,<%= @post.longitude.to_f %>">GoogleMapで詳しく見る</a>'

  const infowindow = new google.maps.InfoWindow({
    content: contentString,
  });

  const marker = new google.maps.Marker({
    position: {lat: <%= @post.latitude.to_f %>, lng: <%= @post.longitude.to_f %>},
    map: map,
    title: "<%= @post.title %>",
  });

  marker.addListener("click", () => {
    infowindow.open({
      anchor: marker,
      map,
    });
  });
}

$(function(){
    let raty_show<%= @post.id %> = document.querySelector('#rate_show<%= @post.id %>');
    rate_show<%= @post.id %>.innerHTML = ""
    let option_show<%= @post.id %> = {
        starOn: "<%= asset_path('star-on.png') %>",
        starOff: "<%= asset_path('star-off.png') %>",
        starHalf: "<%= asset_path('star-half.png') %>",
        score: "<%= @post.rate %>",
        readOnly: true,
      };
    raty(raty_show<%= @post.id %> ,option_show<%= @post.id %>);
});
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap" async defer></script>