config/routes.rb
Rails.application.routes.draw do

  # 管理者用
  devise_for :admin,skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: 'homes#top'
    get 'search' =>"searches#search"
    resources :customers
    resources :posts do
      # resource :favorites, only: [:destroy]
      resources :comments, only: [:destroy]
    end

  end

  # ユーザー用
  devise_for :customers,controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions',
    passwords: 'public/passwords'
  }

  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    root to: 'homes#top'
    resources :notifications, only: :index
    get 'about'=>"homes#about",as: "about"
    get 'search' =>"searches#search"
    get 'favorites_ranking' =>"posts#favorites_ranking"
    get 'follow_posts' =>"posts#follow_posts"
    get 'my_posts' =>"posts#my_posts"
    resources :posts do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end

    resources :customers do
      member do
        get :favorites
      end
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'

    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FamilyOutingApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <header>

      <nav class="navbar navbar-expand-lg navbar-light" style="" >
        <div class="container">
          <a class="navbar-brand text-primary" href="/">
            <%=image_tag "twitter_header_photo_1.png",size:"200x200" , class:"img-fluid"%>
          </a>
          <button class="navbar-toggler navbar-toggler-right border-0" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <ul class="navbar-nav ml-auto">
              <% if customer_signed_in? %>
                <div class = "d-flex align-items-center" style="font-size:15px">
                  ようこそ、<%= current_customer.account_name %>さん !!
                </div>
                <li class="nav-item"><%= link_to  destroy_customer_session_path, class: 'nav-item nav-link', method: :delete do %><i class="fas fa-sign-out-alt"></i>:ログアウト<% end %></li>
                <li class="nav-item"><%= link_to  new_post_path, class: 'nav-item nav-link' do %><i class="fas fa-plus"></i>:投稿<% end %></li>
                <li class="nav-item"><%= link_to  posts_path, class: 'nav-item nav-link' do %><i class="far fa-newspaper"></i>:投稿一覧<% end %></li>
                <li class="nav-item"><%= link_to customer_path(current_customer.id), class: 'nav-item nav-link' do %><i class="fas fa-user"></i>:マイページ<% end %></li>
                <li class="nav-item"><%= link_to  customers_path, class: 'nav-item nav-link' do %><i class="fas fa-users"></i>:ユーザー一覧<% end %></li>
                <li class="nav-item"><%= render "public/partial/circle" %></li>
              <% elsif admin_signed_in? %>
                <div class = "d-flex align-items-center" style="font-size:25px">
                  管理者用
                </div>
                <li class="nav-item"><%= link_to destroy_admin_session_path, class: 'nav-item nav-link', method: :delete do %><i class="fas fa-sign-out-alt"></i>:ログアウト<% end %></li>
                <li class="nav-item"><%= link_to admin_customers_path, class: 'nav-item nav-link' do %><i class="fas fa-users"></i>:ユーザー一覧<% end %></li>
                <li class="nav-item"><%= link_to admin_posts_path, class: 'nav-item nav-link' do %><i class="far fa-newspaper"></i>:投稿一覧<% end %></li>
              <% else %>
                <li class="nav-item"><%= link_to about_path, class: 'nav-item nav-link' do %><i class="fas fa-globe-asia"></i>:About<%end%></li>
                <li class="nav-item"><%=link_to new_customer_session_path, class: 'nav-item nav-link' do %><i class="fas fa-sign-in-alt"></i>:ログイン<% end %></li>
                <li class="nav-item"><%=link_to  new_customer_registration_path, class: 'nav-item nav-link' do %><i class="far fa-handshake"></i>:新規登録<% end %></li>
                <li class="nav-item"><%= link_to customers_guest_sign_in_path, class: 'nav-item nav-link', method: :post do %><i class="fas fa-sign-in-alt"></i>:ゲストログイン<% end %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
      <% if customer_signed_in? %>
      <ul class="navbar-nav ml-auto">
         <li class="text-center"><%= render 'public/searches/form' %></li>
      </ul>
      <% end %>
      <% if admin_signed_in? %>
      <ul class="navbar-nav ml-auto">
         <li class="text-center"><%= render 'admin/searches/form' %></li>
      </ul>
      <% end %>

    </header>
    <main>

      <% flash.each do |message_type, message| %>
        <p class="alert alert-info"> <%= message %></p>
      <% end %>


      <%= yield %>
    </main>

    <footer class="border-top">
      <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
          <div class="col-md-10 col-lg-8 col-xl-7">
            <ul class="list-inline text-center">
              <li class="list-inline-item">
                <%= link_to "https://github.com/yellow-young-chicken/family_outing_app.git", target: :_blank, rel: "noopener noreferrer" do %>
                 <i class="fab fa-github-square fa-3x"></i>
                <% end %>
                </a>
              </li>
            </ul>
          <div class="col-md-12 text-center">
            <a href="/">
            <p class="mb-0">Family Outing</p>
            </a>
          </div>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>